# Generated by Django 5.1.6 on 2025-02-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер класу')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва матеріалу')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва предмету')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(blank=True, null=True, verbose_name='Номер уроку')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=255, verbose_name='Зміст уроку')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Час')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис уроку')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Домашнє завдання')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.grade', verbose_name='Клас')),
                ('materials', models.ManyToManyField(blank=True, to='planner.material', verbose_name='Матеріали')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.subject', verbose_name='Предмет')),
            ],
        ),
    ]
